### ISSUE TITLE
Select Date Range: validation absent - it is possible to set 'to' date earlier than 'from' date

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#1]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click "Select Date Range" button 
3. set 'from' date = 01/01/2008 
4. set 'to' date using calendar =  09/19/2007
5. click Save

_Result:_
Values saved.  validation absent - it is possible to set 'to' date earlier than 'from' date  (see screenshot 737) 
![737](https://cloud.githubusercontent.com/assets/13001938/8284548/080c692c-1906-11e5-98b8-9c7f3bf40d72.png)

_Expected result:_
There should be validation when 'to' date earlier than 'from' date.
Message should appear: "Check your date ranges."

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

As part of miscellaneous data validation changes, I have implemented a fix for the reported issue in my local application build...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

For first release 

Align date fields 'From' and 'Two' under 'Select Date Range...'  button
Move date fields on main page closer together.

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

Checks for 'From' date later than 'To' date included in other fixes...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, warning message was added (see screenshot attached)
![142](https://cloud.githubusercontent.com/assets/13001938/9247352/0e2d4276-41bb-11e5-9d67-4629cc722abd.png)

Fixed with minor defect - https://github.com/CUAHSI/HISWebClientIssues/issues/50
Closed
