### ISSUE TITLE
Download Timeseries: incorrect file name (file name contain current search value instead of selected map area name)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#10]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Search for location (for example Washington DC)
3. Navigate to other location using map (for example Dallas) 
4. Open Data tab. Select any timeseries to download. Than download file.
5. Pay attention to the file name.

_Result:_
incorrect file name (file name consider current search value instead of selected map area name)
(refer to screenshot 737)

_Expected result:_
File name should contain the name of actual selected for search area. In current described case it should be Dallas.

**Comment by Stref** [comment]
![741](https://cloud.githubusercontent.com/assets/13001938/8308985/902b4f24-19d0-11e5-9ce9-0aeddbdd8d06.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix 

Have developed and tested a fix in my local build.  Need to review with team...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

For first release
- Change 'list of time series for' to 'list of time series near'

If time permits, implement user entered zip file name when 'auto download' is not selected.

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all required first release changes specified by review meeting.

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, file name tittle meet selected search area

CLosed
