### ISSUE TITLE
Download Manager (usability): downloaded series are deleted from download manager series after there was attempt to download it

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#11]
_Preconditions:_
1. Search completed. There was found few timeseries which are available for downloading.

_Steps to reproduce:_
1. Open Data tab
2. Select any timeseries
3. Click "Zip Selection" button
4. Wait while task will be completed and open Download Manager
5. Click Download for selected series, then click Cancel
7. Check Download Manager table

_Result:_
Series are deleted from download manager table

_Expected result:_
There can be a number of reasons why user stop or cancel current download (slow internet connection, insufficient drive space and etc).

We suggest you to keep in download manager all tasks (pending download or already downloaded).
Moreover it will help user to remember what he actually have downloaded, that will be more user friendly from our side.

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Reject

Removal of cancelled Download Manager task records functions as designed.  Once stopped, a timeseries processing cannot be re-started.  In these cases, the user must re-select the timeseries and submit a new processing request...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Proposed resolution accepted as is...

**Comment by Stref** [comment]
Won't fixed
Closed according to comments above
