### ISSUE TITLE
Select Date Range: impossible to select date using calendar if previously blank date field was Saved

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#12]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click "Select Date Range" button 
3. Delete all data from "From" field 
4. Click Save (error message should appear)
5. Click "Select Date Range" button 
6. Click on "From" field

_Result:_
calendar displayed NaN values  (see screenshot 742) 

_Expected result:_
System should prevent ability to save date ranges with blank fields. If user enter incorrect data there should be warning message and system should ignore entered data.

**Comment by Stref** [comment]
![742](https://cloud.githubusercontent.com/assets/13001938/8322583/62430f00-1a40-11e5-8f8c-f5e5aa8ba407.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Issue should be addressed for fix now under development for issue #5

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Date issues to be fixed per findings for other issues...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, warning message was added (see screenshot attached)
Now it impossible to 'Save' data whith blank fields
![149](https://cloud.githubusercontent.com/assets/13001938/9270076/8f281f2e-4277-11e5-9cb5-759e50fefb19.png)

Closed
