### ISSUE TITLE
Data tab (usability): if search doesn't return any results, data tab should be disabled

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#13]
_Preconditions_:
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Pay attention to Data tab (disabled)
3. Perform Search with criteria that doesn't return any results on selected area (see screenshot  744)

_Steps to reproduce:_
1. Pay attention to Data tab

_Result:_
Data tab now enabled. It doesn't contain any results.

_Expected result:_
if search doesn't return any results, data tab should stay disabled.

**Comment by Stref** [comment]
![744](https://cloud.githubusercontent.com/assets/13001938/8322663/af5b19ee-1a41-11e5-8db8-7e6f704c8e89.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Have developed and tested a fix in my local build.  Need to review with team...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, data tab disabled when search return 'no results' (see screenshot attached)
![151](https://cloud.githubusercontent.com/assets/13001938/9270206/7dd2d9a2-4278-11e5-9e12-38fe275921fd.png)

Closed
