### ISSUE TITLE
(Investigation):  searching for "Water Level" Keyword doesn't return any results

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#14]
During our functional test we have tried to perform search using different combinations of Keywords and map areas. We covered all common keywords and only one keyword never return any results - "Water level". 

We do not mark this as a bug because we can't definitely verify that this is a search mechanism error, but we want pay your attention to this search criteria and ask  you to verify it from your side.

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Additional research...

**Comment by ghost** [comment]
Water level data perhaps not available in QA environment.  

For first release: 

Remove Water Level option from Common keywords.

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Keyword 'Water level' was removed.  Other keywords successfully return values.

Closed
