### ISSUE TITLE
Warning messages: typos in warning message when selecting 2+ keywords and area is 25sq km+

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#15]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Select 2 any keywords
3. Select all services
4. Select area 25 sq  km+
5. Click Search Map

_Result:_
Warning message appeared with typos  (see screenshot 746) 

_Expected result:_
Warning message should be:
Current selected area is [value] sq km and you have selected more than 1 keywords. Please reduce area or number of keywords to 1.

**Comment by Stref** [comment]
![746](https://cloud.githubusercontent.com/assets/13001938/8322933/1a8e6e74-1a46-11e5-8c2a-138f9ac2c194.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Made a number of changes in my local build:  
- Corrected spelling/grammar errors
- Added locale based formatting for all numeric values
- Found/fixed (undocumented??) bug with dialogs displaying Cancel/OK buttons. These dialogs treated 'Cancel' button clicks like 'OK' button clicks.  Added code to recognize the difference...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release 

Accept proposed fix as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, warning message was edited (see screenshot attached)
![152](https://cloud.githubusercontent.com/assets/13001938/9270238/c901c7d0-4278-11e5-801c-3f079825d60a.png)

Closed
