### ISSUE TITLE
Select Keywords: impossible combine "Common" keywords with keywords from Full list

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#17]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click "Select keyword(s)" button
3. Select any 1  Common keyword
4. Switch to Full list tab 
5. Select any 1 Keyword  from full list
6. Click Save
7. Check selected Keywords from Keyword list under "Select Keyword(s)" button

_Result:_
Only keyword from full list is selected. impossible to combine "Common" keywords with keywords from Full list

_Expected result:_
- If such ability supported - It should be available to select keywords combination from common and full list.
- If such ability shouldn't be supported, there should be appropriate warning message when user try to select keywords from different tabs at the same time.

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Reject

Application functions as designed - combination of 'Common' and 'Full' keyword selections not supported...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release:

Revise logic to allow selection(s) from either or both tabs.  On full tab - indicate selections from common tab, if any.  Display a count of selected items on upper full tab.

**Comment by ghost** [comment]
BCC - 09-Jul-2015 

Completed all items required  by review meeting for first release except for selected items count.  After looking at the current screen design, I did not think the selected items count would prove helpful...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed:
1) it is possible to combine keywords from both lists
2) selected keywords from common list are indicated at full list
3) **Count of selected items on upper full tab are not realised**

Remain this issue opened due to 3rd not realised option. But QA agree with ANightCoder-Brian comment above, _we did not think the selected items count would prove helpful_

Please close this issue if 3rd option won't be fixed.

**Comment by ghost** [comment]
BCC - 18-Aug-2015 - Reviewed issue.

Recommendation: No need to include selected item count at this time...

**Comment by ghost** [comment]
Fixed - per 18-Aug-2015 comments...
