### ISSUE TITLE
Select keywords. Full list: some keyword titles are truncated 

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#18]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click  "Select keyword(s)" button
3. Switch to Full list tab
4. Open for example "Chemical -> Organic-> Other organic chemical"
5. Pay attention to items with long titles

_Result:_
Some keyword titles are truncated.  If you mouse over this titles no prompt will be shown  (see screenshot 749) 

_Expected result:_
Add 'alt' to the keyword list. When mouse over long title prompt should be shown. 

NOTE: the issue is common for keyword list at main page (see screenshot 748)

**Comment by Stref** [comment]
![749](https://cloud.githubusercontent.com/assets/13001938/8323615/8271bf10-1a4f-11e5-89ef-a7cd0c9938d9.png)

**Comment by Stref** [comment]
![748](https://cloud.githubusercontent.com/assets/13001938/8323622/9e6072c0-1a4f-11e5-9ea6-4f5aeec07310.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: More research

Inspection of cited fancytree nodes with Chrome development tools confirms no text is truncated by the fancy tree node.  Yet text appears truncated.  Need to determine where text truncation occurs...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release: 

Martin to check on the following:

More research required to determine source of truncation.  Initial findings indicate the data service is not truncating any values.  Need to check JSON handling and fancytree handling of long strings.

**Comment by ghost** [comment]
BCC - 07-Jul-2015

In a conversation today, Martin confirms no truncation of keyword titles occurs in the services or the web client.  No changes required for first release...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
No fix was applied
Close this issue according to comment above

> In a conversation today, Martin confirms no truncation of keyword titles occurs in the services or the > web client. No changes required for first release...

Please note, that from QA side this is a bug.
Closed
