### ISSUE TITLE
Long time map search (enhancement): add progress bar and divide map area for a number of smaller parts

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#19]
In some cases, especially when we select many keywords and set large map area, searching takes about 1 minute to complete (see screenshot 750)

![750](https://cloud.githubusercontent.com/assets/13001938/8323839/436f3bf0-1a52-11e5-9e27-c87a09b6ac92.png)

This behavior is not user friendly. We recommend you:
1) Add progress bar that will inform user actual search status (in percentages for example).

For preventing timeouts (another problem when perform long time search):
2) As i can see from IE page debugger - now portal make one single request for whole selected map area. I suggest you for 'hard' searches with large area and big amount of keywords to divide selected map area for several parts and make number of different requests one by one for every part of area.

(Based on 2nd case you can realize 1st case: when X of Y total map requests got response - progress bar display progress as X/Y*100 )

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: More research...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Suggested tiling mechanism already implemented.

Backend logic divides work among several tasks.  No changes required on front end...

**Comment by Stref** [comment]
Close issue according to comment above:

> Backend logic divides work among several tasks. No changes required on front end...
