### ISSUE TITLE
Google Map (usability): 'Search' button is absent near search location field

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#2]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at google map search field
3 Enter some place to search (for example 'Minsk')

_Result:_
'Search' button is absent near search location field and hardware 'Enter' button doesn't process any action. As a result the User can't navigate to location that he have search for. (refer to screenshot 724)

_Expected result:_
- We suggest you to add "Search" button at the right of the search field ( see maps.google.com as example, screeenshot 725) 
- We suggest you to add action for hardware "Enter" button, it should duplicate "Search" button action (implementation matches maps.google.com)

**Comment by Stref** [comment]
![724](https://cloud.githubusercontent.com/assets/13001938/8300435/7eefa964-198d-11e5-86f1-0a799fabf951.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Unable to reproduce 

Upon the user entering 'minsk' in the Google map's search field, the application displays a drop-down list of matching place names.  If the user then left-clicks on one of the displayed place names, the application displays the map for the selected place name...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Google search function working as designed.  No changes required.

**Comment by Stref** [comment]
From QA view this is still a bug here. If user navigate to CUASHI site using slow internet or high latency connection he will not see dropdown list timely.

But we Close this issue according to comment above 

> Google search function working as designed. No changes required.
