### ISSUE TITLE
Select Keywords: selected keywords saved even popup were closed without user click Save

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#20]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click  "Select keyword(s)" button
3. Select few keywords
4. Close popup window
5. Click  "Select keyword(s)" button 
6. Pay attention to selected items

_Result:_
selected keywords saved even popup were closed without user click Save

_Expected result:_
when user close popup without saving - all changed data should be rolled back

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Fix implemented and tested in my local application build.  Need to review with group...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Similar issues reviewed previously - this issue should be resolved in the same way...

**Comment by ghost** [comment]
BCC - 07-Jul-2015

This issue should be addressed with changes to be made for issue #17

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed: when user close popup without saving - all changed data are rolled back

Closed
