### ISSUE TITLE
Select Data Services: click outside table closing popup

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#21]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "select data service(s)" button
3 Click outside main table (see screenshot 751)

_Result:_
Popup closed. click outside table closing popup 

_Expected result:_
Popup should be closed if:
- user clicked "Close" button
- user clicked "X" button
- user clicked outside popup

_NOTE_ issue is already reproduced for Download Manager popup

**Comment by Stref** [comment]
![751](https://cloud.githubusercontent.com/assets/13001938/8334535/222e35fa-1aa1-11e5-8d34-3b2ceba67f72.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: More research

Able to reproduce behavior in my local build.  Not sure if it is an issue or 'normal functioning' of Bootstrap modal dialogs...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release 

More research required - check click logic for bottom part of modal dialog

**Comment by ghost** [comment]
BCC - 07-Jul-2015

Additional research found omissions in the use of certain bootstrap classes in modal dialogs (e.g., modal-content, modal-dialog, modal-header, modal-body, modal-footer).  Also, the CUAHSI full-screen apparently conflicted with bootstrap modal settings.  

To address the reported issue, I corrected the use of bootstrap modal classes and removed all references to the CUAHSI screen-full class...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, window now closed as expected:
- user clicked "Close" button
- user clicked "X" button
- user clicked outside popup

Closed
