### ISSUE TITLE
Select Data Services: table size doesn't fit page

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#22]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "select data service(s)" button
3 Try to sort table by all felds  

_Result:_
table size doesn't fit page (see screenshot 752)

_Expected result:_ table column width should adjust automatically according to table content and page size

**Comment by Stref** [comment]
![752](https://cloud.githubusercontent.com/assets/13001938/8334948/4f5bc3ec-1aa3-11e5-8501-6cc234459a3e.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Clarification...

Do not understand the issue as stated...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Current table display/scrolling behavior is acceptable - no changes required.

**Comment by Stref** [comment]
Closed according to comment above:

> Current table display/scrolling behavior is acceptable - no changes required.
