### ISSUE TITLE
GUI: popup design do not unified

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#23]
_Steps to reproduce:_
1. navigate to http://qa-hiswebclient.azurewebsites.net/
2. Compare design of "select keywords" popup with "'Select Data Services" or "Download manager"
see screenshots below

_Result:_ popup design do not unified. At the current moment doesn't unified next popups:
- select data services
- download manager

_Expected result:_ all portal windows\popups should have unified design

**Comment by Stref** [comment]
![756](https://cloud.githubusercontent.com/assets/13001938/8350969/7b9bb716-1b32-11e5-94d4-29fcbff83525.png)
![755](https://cloud.githubusercontent.com/assets/13001938/8350970/7b9cd4fc-1b32-11e5-9b62-8c3bd96d7c9c.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Partial Fix 

In my local build - changed 'Select Data Services' header to look more like 'Please select keyword(s)' header.

Dialog scroll bars are NOT 'useless'.  They become active if main window size cannot accommodate dialog size.  

Not sure about rounded vs. sharp corners - presence of scroll bar may be a factor...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release:
Select Data Services - float 'exclude' checkbox to right of screen.

For future release:
Investigate rounded vs. square corners on all dialogs

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed:
- all dialog corners design unified (rounded)
- float 'exclude' checkbox to right of screen
- 'no selections search all' tittle position corrected
  ![155](https://cloud.githubusercontent.com/assets/13001938/9271427/801fd1ec-4282-11e5-9eab-277d68c61981.png)

Closed
