### ISSUE TITLE
Data tab (GUI):  no margins from left and right (need to increase)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#24]
_Preconditions:_
- search was made, there is few result at data tab

_Steps to reproduce:_
1 Open "Data" tab
2 Pay attention to table margins

_Result:_
no margins from left and right  (see screenshot 757)

_Expected result:_ 
there should be margins from left and right

**Comment by Stref** [comment]
![757](https://cloud.githubusercontent.com/assets/13001938/8351795/935fc5b2-1b38-11e5-832b-ad5f74e74ba1.png)

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Fix

In my local application build, added 1.0em right and left margins to 'Data' tab

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, margins added, looks better (see screenshot attached)
![156](https://cloud.githubusercontent.com/assets/13001938/9271752/121b8b20-4285-11e5-9c68-8fbd50930e22.png)

Closed
