### ISSUE TITLE
Data tab: table column titles stay in wrong order after sorting table 

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#25]
_Preconditions:_
- search was made, there is few result at data tab

_Steps to reproduce:_
1 Open "Data" tab
2 Sort table by "Keyword"

_Result:_
table column titles stay in wrong order after sorting table  (see screenshot 758)

_Expected result:_ 
table columns should have appropriate titles 

note: issue is also reproduced when making sorting using filters below table

**Comment by Stref** [comment]
![758](https://cloud.githubusercontent.com/assets/13001938/8353789/69c2035c-1b4a-11e5-804d-456fba3fe257.png)

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Fix

Incorrect sizing of table headers occurs in the jQuery Datatable when the containing element, in this case a modal dialog, is populated when invisible. In this case, the browser does not assign sizes to the table cells.  After some research, implemented and tested a fix in my local application build.  The fix calls the Datatable columns.adjust().draw() methods upon the display of the modal dialog (shown.bs.modal) event...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, sorting applies correctly

Closed
