### ISSUE TITLE
Data tab: filters under the timeseries table have no titles

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#26]
_Preconditions:_
- search was made, there is few result at data tab

_Steps to reproduce:_
1 Open "Data" tab
2 Pay attention to the filters under the timeseries table

_Result:_
filters under the timeseries table have no titles  (see screenshot 759)

_Expected result:_ 
There should be title like (Organization Filter, "Service Name Filter", "Variable Name Filter"

**Comment by Stref** [comment]
![759](https://cloud.githubusercontent.com/assets/13001938/8354052/841300be-1b4d-11e5-9127-021e763cbebe.png)

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Fix

Have implemented a fix in my local build which prepends a disabled option as a 'placeholder' to each filter...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release 
Apply fixes listed in earlier issue.

**Comment by ghost** [comment]
BCC - 07-Jul-2015

Fixes applied as described in issue #46

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, title was added (see screenshot attached)
![145](https://cloud.githubusercontent.com/assets/13001938/9249799/d2b3f954-41d0-11e5-888e-3df809045ec5.png)

Closed
