### ISSUE TITLE
Data tab: page have 2 scroll bars

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#27]
_Preconditions:_
- search was completed, there is few result at data tab

_Steps to reproduce:_
1 Open "Data" tab
2 Pay attention to the scroll bars

_Result:_
page have 2 scroll bars (see screenshot 760)

_Expected result:_ 
There should be only 1 scroll bar

**Comment by Stref** [comment]
![760](https://cloud.githubusercontent.com/assets/13001938/8356035/6a30d44c-1b5b-11e5-8d47-525fd7748346.png)

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend - Close - cannot reproduce

With recent fixes in my local application build, I cannot reproduce the reported problem...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Additional testing suggests this issue is limited to IE default functionality.  

Leave current implementation as is...

**Comment by Stref** [comment]
Closed according to comment above:

> Additional testing suggests this issue is limited to IE default functionality.
> Leave current implementation as is...
