### ISSUE TITLE
Data Tab (usability): archives auto downloaded when user clicked "Zip Selections" without any prompt

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#28]
_Preconditions:_
- search was completed, there is few result at data tab

_Steps to reproduce:_
1 Open "Data" tab
2 Select any entry 
3 click "Zip Selections" button

_Result:_
archive auto downloaded when user clicked "Zip Selections" without any prompt  (see screenshot 759)

_Expected result:_ 
We suggest you to duplicate option "Auto download Archive" from Download Manager popup to the Data tab. Or as an alternative way - add 2 button to the "Data Tab": one - "Zip Selections", second - "Zip and Download selection". This will be more clear for users what actually should happened when they click button.

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Reject

Auto Download feature functions as designed...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Recommendation accepted as is..  

For first release - refer to Jon's internal QA issue - #27

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Closed according to comment above

> Recommend: Reject
> Auto Download feature functions as designed...
