### ISSUE TITLE
GUI: "No timeseries for specified parameters found" have different font size.

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#29]
Steps to reproduce:
1 perform search on a very small areea with 1 keyword and 1 data service (selected area shouldn't have any data )

Result:
Warning message "No timeseries for specified parameters found." have font size that differ from other messages. (see screenshots below)

Expected Result: 
All system messages should have unified design (font, color, format)

**Comment by Stref** [comment]
![761](https://cloud.githubusercontent.com/assets/13001938/8356620/26487f38-1b5f-11e5-9679-0b9359a3227b.png)
![745](https://cloud.githubusercontent.com/assets/13001938/8356623/2bc7278e-1b5f-11e5-819b-9e7aed98dfd8.png)
![762](https://cloud.githubusercontent.com/assets/13001938/8356647/41680a22-1b5f-11e5-8b87-a3b9c571b54d.png)
![762](https://cloud.githubusercontent.com/assets/13001938/8356658/4fa8ab64-1b5f-11e5-970e-650b9abca28f.png)
![763](https://cloud.githubusercontent.com/assets/13001938/8356663/5185d61e-1b5f-11e5-90be-4b6b62a71e37.png)

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Fix

Issue fixed in my local application build...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release 

If time permits add titles to dialogs - otherwise proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, warning message text inified
Closed
