### ISSUE TITLE
Google Map (usability): unnecessary "street view" button

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#3]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at map
3 Click on street view button (drag icon to the map)

_Result:_
Google street view has opened. (refer to screenshot 726)
User can't navigate back to normal map view.

_Expected result_
There is not necessary to use "street view" functionality, button should be hidde

**Comment by Stref** [comment]
![726](https://cloud.githubusercontent.com/assets/13001938/8300445/9e76edce-198d-11e5-87b8-a183b832d9ef.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: fix

Fix applied to local build and tested...

Fix comment: //BCC - 26-Jun-2015 - QA Issue #3 - Remove steet view control, including 'peg man' icon from map

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

For first release:

Would like to retain street view.  Back out local fix.

Martin to investigate how to return to previous (map) page from streetview...

**Comment by ghost** [comment]
BCC - 07-Jul-2015

Testing confirms Martin's fix provides a convenient means to return to the map display from the street view display...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, exit from street view button was added. See screenshot:
![146](https://cloud.githubusercontent.com/assets/13001938/9250354/e23af018-41d4-11e5-8855-1a2cfe446428.png)

Closed
