### ISSUE TITLE
Select Data services: "Exclude Gridded data services..." function work incorrect

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#30]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "select data service(s)" button
3 Select few data services (5 for example)
4 Click "Exclude Gridded data services"

_Result:_
System has selected all entries from a list except "Gridded data services"
Such behavior will be correct for option "Select all data service Exclude Gridded data services"

_Expected result:_
According to function title "Exclude Gridded data services" expected result will be: exclusion gridded data services from those, which user have selected (those entries can be removed from the table when option is active).

**Comment by ghost** [comment]
BCC - 29-Jun-2015 - Recommend: Reject

Do not understand the stated issue.  Application appears to function as designed...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release
Change button text to 'Select all non-gridded ...'

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, button text changed (see screenshot attached)
![158](https://cloud.githubusercontent.com/assets/13001938/9278119/33166b7e-42b7-11e5-8e6a-a90619cd8ef9.png)
closed
