### ISSUE TITLE
Download Manager: close button is absent

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#31]
Steps to reproduce:
1. Open Download manager
2. Check for Close button

Result: 
close button is absent (see screenshot)

Expected result:
all website elements should have unified design and navigation elements. Download Manager  should have "Close" button

**Comment by Stref** [comment]
![764](https://cloud.githubusercontent.com/assets/13001938/8357668/cf8a0bd4-1b64-11e5-8113-8d4fa1634000.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

Like many other application dialogs, Download Manager features an 'x' in the upper right hand corner.  Left-clicking the 'x' closes the dialog.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Recommendation accepted as is...

**Comment by Stref** [comment]
Close according to comment above

> Recommendation accepted as is
