### ISSUE TITLE
General GUI: no scroll bar when reduce page size (menu items can become unavailable)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#34]
_Steps to reproduce:_
1. Go to http://qa-hiswebclient.azurewebsites.net/
2. Select few Keywords 
3. Reduce page size 

_Result:_ 
no scroll bar when reducing page size (menu items can become unavailable)  (see screenshot below)

_Expected result_:
when some page elements can't be resized to fit page size - scroll bar should appear

**Comment by Stref** [comment]
![767](https://cloud.githubusercontent.com/assets/13001938/8377199/d172ac04-1c17-11e5-8503-45b7c47e48dc.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

In my local application build have added an automatic vertical scrollbar to the search parameter panel.  Please note, a horizontal scroll bar is not needed since the panel remains visible whenever the user narrows the main window...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Scroll bar was added
![160](https://cloud.githubusercontent.com/assets/13001938/9278374/16cd9878-42b9-11e5-8470-960d31843d4a.png)

Closed
