### ISSUE TITLE
(cross-browser) Safari: after page reloading right menu  truncated

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#35]
_Steps to reproduce:_
1. Open http://qa-hiswebclient.azurewebsites.net 
2. reload page (F5)

_Result:_ 
after page reloading right menu  truncated (see screenshot below)

_Expected result:_
main page displayed without changes, all elements present at actual size

**Comment by Stref** [comment]
![768](https://cloud.githubusercontent.com/assets/13001938/8379255/67212406-1c27-11e5-8cb8-f7304902d578.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

Tests with my local application build under Safari and Windows 7 cannot reproduce the reported issue.  However, under Safari the search panel appears closed when the web page loads.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release 
Re-test on Safari on an Apple machine.  Fix any issues.

**Comment by ghost** [comment]
BCC - 10-Jul-2015

Not able to reproduce on my Apple MacBook Pro running Safari v7.1.6 (9537.85.15.3)
at http://qa-hiswebclient.azurewebsites.net

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Safari 8.0.3 (10600.3.1.18)
Issue is still reproduced
![162](https://cloud.githubusercontent.com/assets/13001938/9278777/bcbcf754-42bb-11e5-89dd-bfc962b5e3a4.png)

Reopened

**Comment by ghost** [comment]
BCC - 18-Aug-2015 - Reviewed reported issue - NOT able to reproduce

Recommendation: Reject

After updating my personal MacBook Pro to OS X Yosemite and running Safari v. 8.0.8 (10600.8.9), I am not able to reproduce the reported issue when linking to the test web site: http://bcc-hiswebclient.azurewebsites.net

**Comment by ghost** [comment]
Fixed - per 18-Aug-2015 comments
