### ISSUE TITLE
Google Map: No possibility to close the Help button or to change its location

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#37]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Change the window size to 1285 x 425 for example
3 Take a look at the Help button

_Result:_
1. The Help button overlaps other buttons (see file attached 8.png)
2. There is no possibility to close the Help button or to change its position.

_Expected result:_
The Help button shouldn't overlap other elements of the application. 
We suggest you to add possibility to close the Help button or to change its location.

**Comment by Stref** [comment]
![8](https://cloud.githubusercontent.com/assets/13001938/8382049/87809cb6-1c38-11e5-982f-97acf7ba5867.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

While the help button does sometimes overlap other controls on the search panel, the overlapped controls remain accessible.  Therefore, this overlapping of controls does not impede application operation.  

For the next release, it might prove helpful to confine the help button in a separate div - thereby ensuring it does not overlap any other control.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Recommendation accepted as is...

**Comment by Stref** [comment]
Won't fixed
Closed according to comments above.
