### ISSUE TITLE
Top menu: the 'Contact' button is trimmed

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#38]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at the 'Contact' button

_Result:_
The 'Contact' button is trimmed (see file attached 17.png)

_Expected result:_
The 'Contact' button should be shown correctly with all boarders like 'Download Manager' button.

**Comment by Stref** [comment]
![17](https://cloud.githubusercontent.com/assets/13001938/8382153/63d61e5c-1c39-11e5-85b7-b02df850362b.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

While the Contact button does appear close to the containing window, it no longer appears trimmed in my local application build...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

If time permits, add some space to the right of the Contact button...

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, space was added (see screenshot attached)

![161](https://cloud.githubusercontent.com/assets/13001938/9278494/c986994c-42b9-11e5-8c15-f6b136f8da81.png)

closed
