### ISSUE TITLE
Right side menu: an extra 's' in the 'Select Data Services(s)' button spelling

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#39]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at the 'Select Data Services(s)' button

_Result:_
an extra 's' in the 'Select Data Services(s)' button spelling (see file attached 18.png)

_Expected result:_
Right spelling: 'Select Data Service(s)'

**Comment by Stref** [comment]
![18](https://cloud.githubusercontent.com/assets/13001938/8382190/9527aaf2-1c39-11e5-8ab9-b95f32e10d36.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

The extra 's' in Select Data Services(s) is removed in my local application build.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, title corrected (see screenshot attached)
![163](https://cloud.githubusercontent.com/assets/13001938/9278822/12e61a34-42bc-11e5-843a-1a92de1d0b7b.png)

Closed
