### ISSUE TITLE
Internet Explorer 9: incorrect default page sizing, scroll-bar always displayed

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#4]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/

_Result:_
incorrect default page sizing, scroll-bar always displayed (refer to screenshot 727)

_NOTE:_ this issue reproduced in Inrernet Explorer 9 (dont reproduced with google Chrome 43). Other browsers will be checked during cross-browser test.

_Expected result_ Portal should be displayed without scroll-bars in default size as on Google Chrome 43

**Comment by Stref** [comment]
![727](https://cloud.githubusercontent.com/assets/13001938/8300464/ca8339cc-198d-11e5-886c-87f8240039e0.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Unable to test - need workstation with IE 9 installed...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Displayed scroll bar is probably due to IE default behavior.  No changes required.

**Comment by Stref** [comment]
Closed according to comment above

> Displayed scroll bar is probably due to IE default behavior. No changes required.
