### ISSUE TITLE
Search is running after closing or clicking 'Cancel' button in the warning message window

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#40]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Choose a map area (less than 100 000 sq km,  for example, 35 764 sq km)
3 Click 'Select Keyword(s)'
4 Select a keyword (for example, Discharge)
5 Click 'Search Map'
6 Click 'Cancel' or close the appeared warning message 'Current selected area is <size> sq km. This search can take a long time. Do you want to continue?'

_Result:_
search is running 

_Expected result:_
1. Search should be running only by clicking 'OK' in the warning message window. 
2. After clicking the 'Cancel' button or closing the window search should be canceled

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

In testing earlier issues with the search area warning messages, I noticed the issue described herein.  In my local application build, the cancel button now works correctly on all search warning dialogs.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, after clicking 'Cancel' button or closing the window search canceled

Closed
