### ISSUE TITLE
Popup 'Please select your date range': selected dates are not reset after the popup is closed without saving

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#41]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click the 'Select Date Range' button
3 Select dates (for example, 06/01/2015 and 06/24/2015)
4 Close the popup
5 Click the 'Select Date Range' button
6 Click in the 'From' field
7 Click out of the field and calendar area

_Result:_
After Step 6 the calendar appeares with the dates chosen in Step 3 (see file attached 29.png).
After Step 7 the date chosen in Step 3 appeares in the field (see file attached 30.png).
Selected dates are not reset after the popup is closed without saving

_Expected result_
Selected data should be reset after the popup is closed without saving

**Comment by Stref** [comment]
![29](https://cloud.githubusercontent.com/assets/13001938/8382440/513dff10-1c3b-11e5-9b49-f1cdfc630a6f.png)
![30](https://cloud.githubusercontent.com/assets/13001938/8382448/550d544c-1c3b-11e5-9f4b-0100ff0154ec.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

In testing other date entry changes, I noticed the issue described herein.  The issue is corrected in my local application build...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release:

Disable date entry on main page.  If click in date field on main page - show date dialog.

On date dialog allow type of date or date selection via calendar.  All date format checking handled by calendar.  From date later than to date handled by us.

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, problem doesn't reproduced now

Closed
