### ISSUE TITLE
Popup 'Click to select Data Services': no padding between check box and field name

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#42]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click the 'Select Data Services(s)' button
3 Take a look at the check box

_Result:_
No padding between the check box and the field name (see file attached 37.png)

_Expected  result:_
Should be padding between the check box and the field name

**Comment by Stref** [comment]
![37](https://cloud.githubusercontent.com/assets/13001938/8382586/3a7320ac-1c3c-11e5-80eb-c4e93aa3e26c.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

Added a space between the check box and the label text in my local application build...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is

If time permits and/or future release - revise font usage on screen

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, checkbox moved to the right side of the window 
![158](https://cloud.githubusercontent.com/assets/13001938/9278629/b4849caa-42ba-11e5-8e03-c436e32bf99a.png)

Closed
