### ISSUE TITLE
'Select Data Services(s)': the format of the message that all services are chosen changes

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#43]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at the format of the message in the 'Select Data Services(s)' area
3 Click the 'Select Data Services(s)' button
4 Select some sevices and close the popup
5 Click the 'Select Data Services(s)' button
6 Remove previous selection and close the popup
7 Take a look at the format of the message in the 'Select Data Services(s)' area

_Result:_
formats of the message are different (see file attached 39.png)

_Expected result:_
Equal format of the message when all services are chosen

**Comment by Stref** [comment]
![39](https://cloud.githubusercontent.com/assets/13001938/8382660/e08087aa-1c3c-11e5-9d64-9513cdb83d85.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

In my local application build, revised message logic to display the word 'All' whenever all data services are selected.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, message now displayed correctly

Closed
