### ISSUE TITLE
Popup 'Click to select Data Services': 'Save' button is missed

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#44]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click the 'Select Data Services(s)' button
3 Take a look at the buttons in the popup

_Result:_
the 'Save' button is missed (see file attached 40.png).
The chosen elements are saved automatically by closing the popup.

_Expected result:_
According to the logic of others parameters choise there should be a button 'Save' to save the selection. And it should be possible to close the popup without saving changes.
- We suggest you to add the 'Save' button and to remove the 'Close' button to make the popup equal to another popups for parameters choise (see file attached 41.png)

**Comment by Stref** [comment]
![40](https://cloud.githubusercontent.com/assets/13001938/8382671/005283c6-1c3d-11e5-95f6-fa3a1f5529c5.png)
![41](https://cloud.githubusercontent.com/assets/13001938/8382675/053c3cc4-1c3d-11e5-951b-ece690af56c3.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

In my local application build, changed 'Select Data Service(s)' button text from 'Close' to 'Save'.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release - 

back out change - restore original functionality

Add 'clear all selections' button.  Enable whenever any selections are made, disable whenever no selections are made.

**Comment by ghost** [comment]
BCC - 06-Jul-2015 

After completing issue # 45, found it rather challenging to 'restore original functionality' here.  

Will return to this issue after completing work on the other QA review meeting changes...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
'Save' button is still not realised. See screenshot attached above

Reopen this issue

**Comment by ghost** [comment]
BCC - 18-Aug-2015 - Reviewed reported issue.

Recommendation: Reject

Per 01-Jul-2015 review meeting findings, the current implementation ('close' button only) will be maintained.

**Comment by ghost** [comment]
Not a bug - design decision mandates use of a 'Close' button not a 'Save' button here - per 18-Aug-2015 comments...
