### ISSUE TITLE
(Enhancement) Popup 'Click to select Data Services': add possibility to select all automatically and to clear the selection

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#45]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click the 'Select Data Services(s)' button

_Result:_
it's not possible to choose all services on the page, for example.
It's not possible to clear the selection.
To clear the selection user has to click each chosen service one more time.

_Expected result:_
1. We suggest you to add possibility to select/disselect all services or all services on the page automatically. 
2. We suggest you to add possibility to clear the selection.

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

If I understand correctly, selecting ALL data services would result in some very long running queries.  Thus, providing an automated means to select all data services is not advisable.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For first release:
- Add 'clear selection' button

**Comment by ghost** [comment]
BCC - 06-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Realised according to comment above

> For first release:
> Add 'clear selection' button

see https://github.com/CUAHSI/HISWebClientIssues/issues/47 for additional information

Closed
