### ISSUE TITLE
(Enhancement) 'List of Timeseries for Selected Marker': an empty line is displayed in drop downs for the absence of filtration

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#46]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Chose the area for example 9103 sq km
3 Click 'Search Map'
4 Click the marker on the map
5 Open the drop down under the first column
6 Take a look at the drop down items 

_Result:_
an empty line is displayed in drop downs for the absence of filtration (see file attached 52.png)

_Expected result:_
We suggest you to add a title for the item of non filtration. For example, 'No filter'

**Comment by Stref** [comment]
![52](https://cloud.githubusercontent.com/assets/13001938/8382787/f0bff352-1c3d-11e5-886a-ef1e326a8c8a.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: More research 

During development of the search filter 'placeholders', I did notice these blank options in the filter selects.  Apparently, jQuery DataTable provides these blank options as a means to remove the currently selected filter.  More research is required to determine whether jQuery Datatable supports customization of such option contents...

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release 

Show the currently selected option in the filter...

If time permits - Attempt to replace the blank option with text like 'No selection'.

**Comment by ghost** [comment]
BCC - 06-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Realised as described in task https://github.com/CUAHSI/HISWebClientIssues/issues/26

Closed
