### ISSUE TITLE
(Enhancement) add possibility to set ALL search parameters to default (reset keywords & services)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#48]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Take a look at the page

_Result:_
it's impossible to set search parameters to default 

_Expected result:_
We suggest you to add button that will allow possibility to set search parameters to default (All keywords and All services)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Additional research

The suggested enhancement may well prove helpful to the user community.  Additional research is required to develop the associated user stories and workflow.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release:
Change 'clear map' button to 'set defaults' - Reset all search parameters to default values.  DO NOT change currently set map co-ordinates but remove all map markers ...

**Comment by ghost** [comment]
BCC - 02-Jul-2015 - 

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Realised according to comment above 

> For First Release:
> Change 'clear map' button to 'set defaults' - Reset all search parameters to default values. DO NOT > > change currently set map co-ordinates but remove all map markers ...

Closed
