### ISSUE TITLE
Map area square calculated incorrectly

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#49]
_Steps to reproduce:_
1. Open http://qa-hiswebclient.azurewebsites.net/
2. Choose any region (for example 'Colorado')
3. Pay attention to the provided calculated area square (sq km)

_Result:_
 map area square calculated incorrectly (see screenshot)
At the screenshot u can see 'Area: 39684'. If u open wikipedia 'Colorado', u can check that area is '269,837 km2' https://en.wikipedia.org/wiki/Colorado

_Expected result:_
map area should calculate correctly

**Comment by Stref** [comment]
![772](https://cloud.githubusercontent.com/assets/13001938/8520980/297c2948-23e8-11e5-8203-28ab963cd67c.png)

**Comment by martinseul** [comment]
fixed
