### ISSUE TITLE
Select Date (usability): add possibility to edit data from main page (popup window can be removed)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#5]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click into the field under "Select Date Range" button (for example "From:")
3 Try to edit data using keyboard

_Result:_
it's impossible to edit data using keyboard (editing restricted)
(refer to screenshot 731)
User need to make several actions to enter data criteria.  (click Select Date Range button, then input values, then click save..)

_Expected result:_
- We suggest you to add possibility enter data from keyboard by editing fields "from" and "to" right at the main page. 
- We suggest you to remove "Please select your date range:" popup (see screenshot 732)

**Comment by Stref** [comment]
![731](https://cloud.githubusercontent.com/assets/13001938/8300496/33d2ac0a-198e-11e5-8717-421f548248f5.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Have applied a partial fix to my local build.  Need to complete partial fix and review with team...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

For first release
Edit via date dialog only... But clicking in main page date fields will open date dialog.

**Comment by ghost** [comment]
BCC - 07-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Realised according to comment above

> For first release
> Edit via date dialog only... But clicking in main page date fields will open date dialog.

Closed
