### ISSUE TITLE
(minor) Select Date Range: possible to select 31th day of any month 

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#51]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click "Select Date Range" button 
3. type into "From" date for example 09/31/2015 (september have 30 day)
4. click 'Save'

_Result:_
 possible to select 31th day of any month 
![164](https://cloud.githubusercontent.com/assets/13001938/9301666/da9f0cac-44d8-11e5-8ab0-c0e4c234fdaf.png)

_Expected result:_
Warning message should appear

**Comment by ghost** [comment]
BCC - 18-Aug-2015 - Reviewed and reproduced reported issue.

Recommendation: Fix

Proposed fix: Changes to 'blur' event handlers for the 'From' and 'To' date fields to stop event processing if any event handler encounters an invalid date.

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Already fixed

On the date entry dialog:
- If the user types in an invalid date and then tabs to the next field, in good JavaScript fashion, the date dialog 'promotes' the entry to the next valid date: (e.g., 9/31/2015 ==> 10/01/2015)
- If the user types in an invalid date and then clicks the 'Save' button, the date dialog displays a 'Please enter a valid date' error message...

**Comment by ghost** [comment]
Fixed - per 31-Mar-2016 comments...
