### ISSUE TITLE
(enhancement) List of timeseries: horizontal scroll bar placed on the bottom of the table(>25 results at page)

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#52]
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Perform Map Search
3. Open Data tab
4. Set 'Show 25 entries' per page

_Result:_
horizontal scroll bar placed on the bottom of the table(>50 results at page)
![157](https://cloud.githubusercontent.com/assets/13001938/9302028/f0bf7a96-44db-11e5-982f-48cc1430f22c.png)

_Expected result:_
Place scroll bar at the bottom of the Browser. This will prevent user from scrolling page down to make side scroll.

**Comment by ghost** [comment]
BCC - 17-Aug-2015 - Reviewed and reproduced reported issue.  

Recommendation: Fix

Proposed Fix: Modified Datatables configuration to include settings: 'scrollY' and 'scrollCollapse' to allow dynamic inclusion of a vertical scroll bar when datatable contents (i.e., number of rows selected for display) exceed the capacity of the browser viewport.    

In these cases, the header and footer areas of the datatable remain in view at all times.  The vertical scroll bar allows the user to scroll through the table rows as shown below:

![image](https://cloud.githubusercontent.com/assets/7917808/9316036/bc61bb40-4500-11e5-8160-b6cd42d34194.png)

**Comment by ghost** [comment]
Not a bug - extensive changes to HydroClient layout since 17-Aug-2015 make this issue obsolete...
