### ISSUE TITLE
(minor) The button "Search map" is enabled when map is zoomed out

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#53]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Zoom out the map
3. Note the button "Search map"

Result:
The button "Search map" is enabled when map zoomed out (see att.)
![1](https://cloud.githubusercontent.com/assets/17844881/13779858/21ea2d9e-eace-11e5-9cf7-08073e8102cc.png)

Expected result:
The button "Search map" isn't enabled when map is zoomed out

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed

Added code to restrict Zoom levels of Google Map: minZoom - 5, maxZoom - 15...

**Comment by ghost** [comment]
Fixed - added logic to disable 'Search Map' button, display error message in button tooltip whenever HydroClient disables searching...
