### ISSUE TITLE
(minor) Map: icon "Like" ("Dislike") duplicated when click "Reset"

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#54]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click the button "Reset"
3. Note the icon "Like" ("Dislike")

Result:
Icon "Like" ("Dislike") duplicated when click "Reset" (see att.)
![2](https://cloud.githubusercontent.com/assets/17844881/13780412/684d375c-ead0-11e5-8954-b97a2fc8f99e.png)

Expected result:
One icon "Like" ("Dislike") is displayed after click "Reset"

**Comment by ghost** [comment]
Fixed - revisions to map initialization logic...
