### ISSUE TITLE
(average) Quick Start: guide isn't displayed on the tabs "Overview", "Search", "Workspace"

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#55]
Environment: win7+ie11

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "About"
3. Click "Quick Start"
4. Note the tab "Overview"
5. Open and note "Search" tab
6. Open and note "Workspace" tab

Result:
Guide isn't displayed on the tabs "Overview", "Search", "Workspace" (see att.)
![3](https://cloud.githubusercontent.com/assets/17844881/13781356/1b0d8b6e-ead4-11e5-8a4e-c712874206e5.png)

Expected result:
Guide is displayed on the tabs "Overview", "Search", "Workspace"

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Not able to reproduce
- Under Windows 7, updated IE to v11.0.9600.17843
- Folllowed steps to reproduce
- As shown below, Quick Start Guide displays as expected

![image](https://cloud.githubusercontent.com/assets/7917808/14148961/d0fe3904-f66f-11e5-8303-dc8f60b46d19.png)

**Comment by ghost** [comment]
Fixed per 30-Mar-2016 comments...
