### ISSUE TITLE
(average) Search: no time series found when check keywords from full list which include another keywords

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#56]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Zoom in the map while the button "Search map" disabled
3. Click "Select keywords"
4. Open "Full list" tab
5. Check keywords which include another keywords (for example, "Physical", "Temperature", etc.)
6. Click "Save"
7. Click "Search map"

Result:
No time series found when check keywords from full list which include another keywords (see att.)
![4](https://cloud.githubusercontent.com/assets/17844881/13782849/e881c614-ead9-11e5-94cf-9f4bc57d4061.png)
![5](https://cloud.githubusercontent.com/assets/17844881/13782850/e8829b84-ead9-11e5-9f4c-3d84e0f1dcf5.png)
![6](https://cloud.githubusercontent.com/assets/17844881/13782851/e8847e9a-ead9-11e5-8e98-008b2a46f315.png)

Expected result:
All time series found which correspond to selected keywords (from another level of hierarchical tree)

**Comment by ghost** [comment]
BCC - 29-Mar-2016 - Not able to reproduce

As shown below, after following the steps to reproduce, search results display on the map...

![image](https://cloud.githubusercontent.com/assets/7917808/14125364/d8779870-f5d8-11e5-8fca-b02efeac7174.png)

**Comment by ghost** [comment]
More investigation required - testing on data.cuahsi.org encounters a '500' server error

**Comment by ghost** [comment]
15-Nov-2016 - Further investigation indicates SOLR catalog returns a 414 - Request-URI too long for searches involving numerous keywords (e.g., all 'Physical' keywords selected on the 'Full' tab on the Keywords Dialog).

**Comment by ghost** [comment]
23-Nov-2016 - After some additional research, applied the following fix:

When processing the user’s search criteria:
  If the user selects ‘ALL’ keywords, conduct the search as previously.
 Otherwise, for each selected keyword – retrieve the titles for all descendant leaves in the ontology tree
	If the combined character length of all the leaf titles exceeds a pre-defined maximum (i.e., 4096)
           display the error message shown below
	Otherwise, perform the search 

For more information please see commit: 4573303 in the QA branch
