### ISSUE TITLE
(major) Workspace: some time series don't have a value in "Variable Units"

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#57]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Select some time series
5. Add selected time series to "Workspace"
6. Click "Open Workspace"
7. Note the values in "Variable Units"

Result:
Some time series don't have a value in "Variable Units" (see att.)
![7](https://cloud.githubusercontent.com/assets/17844881/13790243/8527619a-eaf8-11e5-9eee-b4af8b09defe.png)

Expected result:
All time series have a value in "Variable Units"

Note: time series can't be saved as CSV and loaded to Time Series Viewer if its don't have a value in "Variable Units" - errors occur (see att. below)
![8](https://cloud.githubusercontent.com/assets/17844881/13790405/56267376-eaf9-11e5-9601-9828355c6a01.png)
![9](https://cloud.githubusercontent.com/assets/17844881/13790424/673bfa5a-eaf9-11e5-938d-82921965d9d8.png)

**Comment by ghost** [comment]
BCC - 29-Mar-2016 - fixed

Revised controller's variable units retrieval logic to ensure variable unit for each time series is retrieved before HydroClient stops status checking.

**Comment by ghost** [comment]
Fixed - Changes in SOLR catalog allow HydroClient to retrieve variable units data as part of initial search...
