### ISSUE TITLE
(minor) Scrollbar is displayed for keywords section when selected less than 7 keywords

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#58]
Environment: win7+ie11, win7+FF, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Note the scrollbar in keywords section
3. Click "Select Keywords"
4. Check 6 keywords
5. Click "Save"
6. Note the scrollbar in keywords section

Result:
Scrollbar is displayed for keywords section when selected less than 7 keywords (see att.)
![10](https://cloud.githubusercontent.com/assets/17844881/13805552/a8bb20b0-eb66-11e5-8619-20759c750992.png)

Expected result:
Scrollbar isn't displayed for keywords section when selected less than 7 keywords

**Comment by ghost** [comment]
BC - 15-Nov-2016 - Fixed
For more information see Repository: HISWebClient, Branch: QA, commits:  6fa1176, e1607f
