### ISSUE TITLE
(minor) Scrollbar in keywords section is trimmed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#59]
Environment: win7+ie11, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Select Keywords"
4. Check more than 6 keywords
5. Click "Save"
6. Note the scrollbar in keywords section

Result:
Scrollbar in keywords section is trimmed (see att.)
![11](https://cloud.githubusercontent.com/assets/17844881/13805724/faf41ab6-eb67-11e5-8d46-bd287a8e6578.png)

Expected result:
Scrollbar in keywords section isn't trimmed

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed 
- Reduced width of keyword list's containing div to ensure scrollbar, whenever visible, appears untrimmed

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed in Safari

Confirmed fix in Safari under OS X...

**Comment by ghost** [comment]
Fixed - per 30-Mar- and 31-Mar-2016 comments...
