### ISSUE TITLE
Select Date: automatic date range changes (when editing "to" date using keyboard) work incorrectly

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#6]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "Select Date Range" button 
3 input range 01/01/2008 to 01/01/2015 (screeenshot 734)
4 then put cursor into "to" field and try to edit 2015 to 2010 for example

_Result:_
value into "From" field has changed to 01/01/201 (see screenshot 735)

_Expected result:_
Automatic date change should apply only after using finished enter value in current filed (when user clicked out the field).

**Comment by Stref** [comment]
![735](https://cloud.githubusercontent.com/assets/13001938/8300516/62944274-198e-11e5-96e1-be7becfa93be.png)

**Comment by Stref** [comment]
![734](https://cloud.githubusercontent.com/assets/13001938/8300553/c15f979a-198e-11e5-9186-cc57f4af46dd.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Issue should be addressed with fix now under development for issue #5

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Issue fixed in work for other date issues...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, automatic data changes was removed.

Closed
