### ISSUE TITLE
(minor) Search results: actions buttons enabled when no time series checked

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#60]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Click "Select Action"

Result:
Actions buttons enabled when no time series checked (see att.)
![12](https://cloud.githubusercontent.com/assets/17844881/13808677/5afd3fc2-eb78-11e5-8c3a-7419a3eef063.png)

Expected result:
Actions buttons disabled while no time series checked

Note: for example, downloading of zip file is available in this case

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed

Revised row counting logic for tables: dtTimeseries and dtMarkers to disable selected dropdown options when no rows are selected...

**Comment by ghost** [comment]
Fixed - per 31-Mar-2016 comments...
