### ISSUE TITLE
(minor) The "Select Data Services" button has incorrect size

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#61]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Note the "Select Data Services" button

Result:
The "Select Data Services" button has incorrect size (see att.)
![13](https://cloud.githubusercontent.com/assets/17844881/13808958/a0be3ab0-eb79-11e5-955b-e082af9aff7e.png)

Expected result:
Text "Select Data Service(s)..." is displayed and entirely fit on the button

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed

Increased button width to display full text...

**Comment by ghost** [comment]
Fixed - per 31-Mar-2016 comments...
