### ISSUE TITLE
(minor) The "Sign in" button has incorrect size

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#62]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Note the "Sign in" button

Result:
The "Sign in" button has incorrect size (see att.)
![14](https://cloud.githubusercontent.com/assets/17844881/13809442/fc8917fa-eb7b-11e5-9a0a-ad16b6bf94a1.png)

Expected result:
The "Sign in" button has correct size, like another buttons in the top menu

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed

Fixed by work in issue #65

**Comment by ghost** [comment]
Fixed - per 31-Mar-2016 comments...
