### ISSUE TITLE
(minor) License Agreement popup: "(Version n.n)" is displayed in header

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#63]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "About"
3. Click "License Agreement"
4. Note the header of the popup

Result:
"(Version n.n)" is displayed in header (see att.)
![15](https://cloud.githubusercontent.com/assets/17844881/13809794/7fc94058-eb7d-11e5-8cc4-99837c0d3436.png)

Expected result:
"(Version _correct number of release version_)" is displayed

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed

Added 'currentVersion' to AppSettings in web.config.  Added reference to 'currentVersion' to index.cshtml

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
