### ISSUE TITLE
(minor) About menu: typo in "LicenseAgreement"

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#64]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "About"

Result:
Typo in "LicenseAgreement" (see att.)
![16](https://cloud.githubusercontent.com/assets/17844881/13809983/75541ea8-eb7e-11e5-8fbc-98a675fe2856.png)

Expected result:
"License Agreement" is displayed

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed

Corrected typo as requested...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
