### ISSUE TITLE
(minor) The "Sign out" button has incorrect size and style

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#65]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Sign in with Google account
3. Note the "Sign out" button

Result:
The "Sign out" button has incorrect size and style (see att.)
![17](https://cloud.githubusercontent.com/assets/17844881/13810102/24607f9a-eb7f-11e5-9b6d-990e1d649ddb.png)

Expected result:
The "Sign in" button has correct size and style, like another buttons in the top menu

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed

Replaced Google Sign-in and Sign-out images with buttons and glyphicons for log-in and log-out...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
