### ISSUE TITLE
(average) Sign out popup: signed out when click "Close" icon

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#66]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Sign in with Google account
3. Click "Sign out"
4. Click "Close" icon in the popup

Result:
Popup closed, user signed out

Expected result:
Popup closed, user still signed in

**Comment by ghost** [comment]
BCC - 29-Mar-2016 - Fixed 

webclient.js - googleFormSubmit(event)
Revised bootbox calls to remove Close button ('x') from the displayed popup.

**Comment by ghost** [comment]
Fixed - per 29-Mar-2016 comments...
