### ISSUE TITLE
(minor) Select Date Range: warning message shown for correct dates in some cases

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#67]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Select Date Range" button 
3. Set 'from' date = 01/01/2008 
4. Set 'to' date using calendar = 09/19/2007 (warning message has appeared)
5. Set 'to' date using calendar = 09/19/2008

Result:
Dates are correct, but warning message still shown to the user (see att.)
![18](https://cloud.githubusercontent.com/assets/17844881/13810616/d2459242-eb81-11e5-9cc3-5460e93b1c70.png)

Expected result:
Dates are correct, warning message should be disabled for that case

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - fixed

Revised date checking logic to distinguish invalid individual dates from invalid 'From' and 'To' date comparisons...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
