### ISSUE TITLE
(Investigation): searching for "Methane", "Evaporation, actual", "Nutrient", "Soil Moisture" keywords doesn't return any results

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#68]
During our functional test we have tried to perform search using different combinations of Keywords and map areas. We covered all common keywords and "Methane", "Evaporation, actual", "Nutrient", "Soil Moisture" keywords never return any results.

We do not mark this as a bug because we can't definitely verify that this is a search mechanism error, but we want pay your attention to this search criteria and ask you to verify it from your side.

**Comment by ghost** [comment]
Not a bug - search results depend on search parameters plus service data.  

One example of a 'Methane' search which returns data:
- Location: Sugar Run, Lycoming County, PA
- Search Area: c. 225 sq km
- Date range: 11/14/2010 - 11/14/2016
- Keywords: Methane
- Services: All non-gridded
