### ISSUE TITLE
(minor) Data Services: "Show entries" drop-down list is displayed near "Clear Selections" button

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#69]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Select Data Services"
3. Note the "Show entries" drop-down list

Result:
"Show entries" drop-down list is displayed near "Clear Selections" button (see att.)
![19](https://cloud.githubusercontent.com/assets/17844881/13811213/5abe37c0-eb85-11e5-993d-e21e3f0d09d9.png)

Expected result:
"Show entries" drop-down list is displayed below the table like on another popups, for example Search Results popup
![20](https://cloud.githubusercontent.com/assets/17844881/13811241/8d683784-eb85-11e5-8af6-203ad42c51a7.png)

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed 

Re-positioned 'Show Entries' dropdown as requested...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
