### ISSUE TITLE
"Select Date range" popup: input field "From" title is missing

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#7]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "Select Date Range" button 
3 Take a look at the field titles

_Result:_
popup: input field "From" title is missing (see screenshot 736)

_Expected result:_
Add title to field "From:"

**Comment by Stref** [comment]
![736](https://cloud.githubusercontent.com/assets/13001938/8300533/89f6d926-198e-11e5-9934-36a29e4fcc4a.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix

Issue should be addressed by fix now under development for issue #5

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Issue fixed in other changes for date validation.

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, tittle was added (see screenshot attached)
![147](https://cloud.githubusercontent.com/assets/13001938/9251990/bf09e644-41de-11e5-98ca-7cd558b72c79.png)
Closed
