### ISSUE TITLE
(minor) Workspace: "Show entries" drop-down list is displayed near "Selections" button

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#70]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Workspace"
3. Note the "Show entries" drop-down list

Result:
"Show entries" drop-down list is displayed near "Selections" button (see att.)
![21](https://cloud.githubusercontent.com/assets/17844881/13811365/3fbb4962-eb86-11e5-91c0-67ead8217f17.png)

Expected result:
"Show entries" drop-down list is displayed below the table like on another popups, for example Search Results popup
![20](https://cloud.githubusercontent.com/assets/17844881/13811369/488ccbc4-eb86-11e5-8bcc-1797b4802dbb.png)

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed 

Re-positioned 'Show Entries' dropdown as requested...

**Comment by ghost** [comment]
Fixed per 30-Mar-2016 comments...
