### ISSUE TITLE
(minor) Search Results: Actions: "Add Selection to Workspace" is displayed if nothing checked

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#71]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Click "Select Action"

Result:
"Add Selection to Workspace" is displayed if nothing checked (see att.)
![22](https://cloud.githubusercontent.com/assets/17844881/13811491/2c7a4cd0-eb87-11e5-853e-bf4db7271413.png)

Expected result:
"Add Selection(s) to Workspace" is displayed if nothing checked

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Already fixed

Followed steps to reproduce in my local build - found the correct button text on 'Show Search Result' dialog...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comments...
