### ISSUE TITLE
(minor) Search Results: incorrect name of "Selections" button

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#72]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Note the "Selections" button

Result:
The "Selection" button is displayed (see att.)
![23](https://cloud.githubusercontent.com/assets/17844881/13811635/1782bc62-eb88-11e5-86a4-82dcbfbaf0c3.png)

Expected result:
The "Selections" button is displayed

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed 

Replaced button text 'Selection' with 'Selections'...

**Comment by ghost** [comment]
Fixed - per 30-Mar-2016 comment
