### ISSUE TITLE
(minor) Workspace: incorrect hint for Time Series Viewer button

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#73]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Workspace"
3. Click "Select tool"
4. Note the hint for "Time Series Viewer"

Result:
Hint "View graph and descriptive statistics of one time series" is displayed (see att.)
![24](https://cloud.githubusercontent.com/assets/17844881/13812017/7968606a-eb8a-11e5-9bdf-7d790265c1ba.png)

Expected result:
Hint "View graph and descriptive statistics for 1-5 time series"

**Comment by ghost** [comment]
Fixed - tooltip wording revised...
