### ISSUE TITLE
(average) Workspace: Time Series Viewer: the "Launch Tool" button enabled if time series with 3 different Variable Units are checked

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#74]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Add any 3 time series with 3 different Variable Units to Workspace
4. Click "Open Workspace"
5. Check all time series
6. Select "Time Series Viewer" from "Select Tool" menu
7. Note the "Launch Tool" button

Result:
The "Launch Tool" button enabled if time series with 3 different Variable Units are checked (see att.)
![25](https://cloud.githubusercontent.com/assets/17844881/13812331/a9ff6870-eb8c-11e5-9680-48487141a137.png)

Expected result:
The "Launch Tool" button enabled if 1-5 time series with 1-2 different Variable Units are checked

Note: error of loading time series is displayed if click "Launch Tool" in this case (see att.)
![26](https://cloud.githubusercontent.com/assets/17844881/13812410/0b098010-eb8d-11e5-87b9-fdd745d75b92.png)

Note2: hint of "Launch Tool" button for Time Series Viewer should be changed if this issue will be fix

**Comment by ghost** [comment]
Changes in Timeseries Viewer alert user to variable units restrictions...
