### ISSUE TITLE
(minor) Time Series Viewer: the "Reset zoom" button is trimmed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#77]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Check any time series and add this timeseries to workspace
5. Click "Open Workspace"
6. Check time serie and load it to Time Series Viewer
7. Zoom in a graph

Result:
The "Reset zoom" button is trimmed (see att.)
![29](https://cloud.githubusercontent.com/assets/17844881/13813996/8d6d8d3c-eb95-11e5-889d-efa2626090da.png)

Expected result:
The "Reset zoom" button isn't trimmed

**Comment by ghost** [comment]
Fixed - Changes in Timeseries Viewer now handle graph 'zooming' differently...
