### ISSUE TITLE
(average) Time Series Viewer: aditional info for time serie differs from time serie info on Workspace tab

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#78]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Check any time series and add this timeseries to workspace
5. Click "Open Workspace"
6. Check time serie and load it to Time Series Viewer
7. Expand aditional time serie info
8. Note the values

Result:
Aditional info for time serie differs from time serie info on Workspace tab (see att.)
![30](https://cloud.githubusercontent.com/assets/17844881/13814355/f5a37d66-eb96-11e5-9aa5-157f6f73860a.png)

Expected result:
Aditional info for time serie doesn't differ from time serie info on Workspace tab

**Comment by ghost** [comment]
Fixed by updates to Timeseries Viewer display logic
