### ISSUE TITLE
(minor) Authorized users: Workspace: service icon for saved time serie changes after re-login

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#79]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Sign in with Google account
3. Search for any time series
4. Click "Show Search Results"
5. Check any time series and add this timeseries to workspace
6. Click "Open Workspace"
7. Note service icons
8. Re-login
9. Click "Workspace"
10. Note service icons

Result:
Service icon for saved time serie changes after re-login (see att.)
![31](https://cloud.githubusercontent.com/assets/17844881/13815169/8bef6c1e-eb9a-11e5-9698-354878799a44.png)
![32](https://cloud.githubusercontent.com/assets/17844881/13815178/94b5d126-eb9a-11e5-9f28-9f391d816db2.png)

Expected result:
Service icon for saved time serie doesn't change after re-login

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed

Revised workspace timeseries save logic to include service code in writes to db.  The service code is the unique key required by one of the CUAHSI services to return the service icon...

**Comment by ghost** [comment]
Fixed per 30-Mar-2016 comments
