### ISSUE TITLE
Select Date Range: warning messages should be shown in same popup

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#8]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Click "Select Date Range" button 
3 set 'from' date = 01/01/20
4 set 'to' date using calendar =  09/19/20
5 click Ok

_Result:_
new popup appeared with warning message (see screenshot 738). After closing popup user lead to the main page 

_Expected result:_
Warning messages should be shown in same popup (in this situation in "Select Date Range" popup). User should have ability to immediately correct values.

**Comment by Stref** [comment]
![738](https://cloud.githubusercontent.com/assets/13001938/8300545/b0125bee-198e-11e5-9bdc-24575d5060cf.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2015 - Recommend: Fix 

Issue should be addressed by fix now under development for issue #5

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Issue fixed in work for other date validation changes...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Issue fixed, warning message appeared in same popup window (see screenshot attached)
![143](https://cloud.githubusercontent.com/assets/13001938/9252043/0eb3663e-41df-11e5-804f-7bc2224e137b.png)
Closed
