### ISSUE TITLE
(minor) Search tab, Workspace tab: horizontal scrollbar is displayed at the bottom of the tabs

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#82]
Environment: win7+ie11, win10+edge

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Note horizontal scrollbar at the bottom of the Search tab
3. Click "Open Workspace"
4. Note horizontal scrollbar at the bottom of the Workspace tab

Result:
Horizontal scrollbar is displayed at the bottom of the Search, Workspace tabs (see att.)
![35](https://cloud.githubusercontent.com/assets/17844881/13839614/6aaf1aac-ec2d-11e5-8cd1-b314d194f740.png)
![36](https://cloud.githubusercontent.com/assets/17844881/13839621/739e6654-ec2d-11e5-9b15-f87afef09edc.png)

Expected result:
Horizontal scrollbar isn't displayed at the bottom of the Search, Workspace tabs

**Comment by ghost** [comment]
Added attributes to <body> tag to suppress scrollbar display in IE and Edge...
