### ISSUE TITLE
(minor) Data Services: the "Select all non-gridded data services" checkbox isn't reseted when click "Reset" on the map tab

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#83]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC,Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Select Data Services"
3. Check the "Select all non-gridded data services" checkbox
4. Click "Close"
5. Click "Reset"
6. Click "Select Data Services"
7. Note the "Select all non-gridded data services" checkbox

Result:
The "Select all non-gridded data services" checkbox isn't reseted when click "Reset" on the map tab, but selections on the Data Services tab are cleared (see att.)
![37](https://cloud.githubusercontent.com/assets/17844881/13839758/b3c64584-ec2e-11e5-8040-2df16b074933.png)

Expected result:
The "Select all non-gridded data services" checkbox is reseted when click "Reset" on the map tab, and selections on the Data Services tab are cleared

**Comment by ghost** [comment]
BCC - 30-Mar-2016 - Fixed

Revised checkbox initialization logic to uncheck on Reset button press...

**Comment by ghost** [comment]
Issue fixed per 30-Mar-2016 comment...
