### ISSUE TITLE
(minor) Time Series Viewer: upper scroll arrow isn't displayed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#84]
Environment: win7+ie11, win10+edge, win7+FF, win7+GC, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Check any time series and add this timeseries to workspace
5. Click "Open Workspace"
6. Check time serie and load it to the Time Series Viewer
7. Note the upper scroll arrow on the Time Series Viewer tab

Result:
Upper scroll arrow isn't displayed on the Time Series Viewer tab (see att.)
![38](https://cloud.githubusercontent.com/assets/17844881/13839922/10e52950-ec30-11e5-8ca5-4b6e6dde667b.png)

Expected result:
Upper scroll arrow is displayed on the Time Series Viewer tab

**Comment by ghost** [comment]
Fixed by changes in Timeseries Viewer layout...
