### ISSUE TITLE
(cross-browser: Edge) (minor) Right-side menu is trimmed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#85]
Environment: win10+edge

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Note the right-side menu and minimize button of menu
3. Click "Select Keywords"
4. Check 9 keywords
5. Click "Save"
6. Note the right-side menu and scrollbar in the keywords section

Result:
Right-side menu is trimmed (see att.)
![39](https://cloud.githubusercontent.com/assets/17844881/13840331/f228ea44-ec32-11e5-8bc8-e6e6d8a4adf7.png)

Expected result:
Right-side menu isn't trimmed

**Comment by ghost** [comment]
BCC - 5-Apr-2016 - Fixed

Revised positioning of side panel toggle as requested.  

Select Keywords issue already fixed by work on issue #87

**Comment by ghost** [comment]
Fixed - per 05-Apr-2016 comments...
