### ISSUE TITLE
(cross-browser: IE 8) (critical) Browser crashes when application is loading

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#86]
Environment: win7+ie8

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/

Result:
Browser crashes when application is loading (see att.)
![40](https://cloud.githubusercontent.com/assets/17844881/13840556/2a3a34b4-ec34-11e5-93ae-9720cf52be40.png)

Expected result:
Application is loaded successfuly

**Comment by ghost** [comment]
HydroClient supports only IE versions 9.0 and later
