### ISSUE TITLE
(cross-browser: GC) (minor) Right-side menu is trimmed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#87]
Environment: win7+GC

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Click "Select Keywords"
3. Check 9 keywords
4. Click "Save"
5. Note the right-side menu and scrollbar in the keywords section

Result:
Right-side menu is trimmed, scrollbar in the keywords section isn't displayed (see att.)
![41](https://cloud.githubusercontent.com/assets/17844881/13842376/db167b26-ec3e-11e5-9a0f-5223570c44b3.png)

Expected result:
Right-side menu isn't trimmed, scrollbar in the keywords section is displayed

**Comment by ghost** [comment]
Cannot reproduce in data.cuahsi.org
