### ISSUE TITLE
(cross-browser: Safari 9.0) (minor) After page reloading right menu truncated

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#88]
Environment: Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Open http://qa-hiswebclient.azurewebsites.net 
2. Reload page (F5)

Result: 
After page reloading right menu truncated (see att.)
![42](https://cloud.githubusercontent.com/assets/17844881/13844052/5606463c-ec48-11e5-9357-337a1e65b032.png)

Expected result:
Main page displayed without changes, all elements present at actual size

**Comment by ghost** [comment]
BCC - 31-Mar-2016 - Fixed

Revised initialization of side panel to ensure display in Safari (and other browsers) upon page reload...
