### ISSUE TITLE
(Mobile) (Critical) All menues are trimmed (impossible to open search results, workspace, about, imposible to sign in)

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#89]
Environment: HTC One M8s, Android 5.0.2

Steps to reproduce:
1. Open http://qa-hiswebclient.azurewebsites.net 
2. Note the menues

Result: 
All menues are trimmed (impossible to open search results, workspace, about tabs, imposible to sign in) (see att.)
![43](https://cloud.githubusercontent.com/assets/17844881/13875103/ebe25aa0-ed0c-11e5-908b-66a4f8f73114.png)
![44](https://cloud.githubusercontent.com/assets/17844881/13875106/f0cfca66-ed0c-11e5-92c4-df4851b24f0f.png)

Expected result:
All application functionality is available for mobile users

**Comment by ghost** [comment]
16-Nov-2016 - Fixed 

Please see HISWebClient - QA branch - commit# 6c027ac for more information...
