### ISSUE TITLE
Timeout error message: typo in word 'occurred'

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#9]
_Steps to reproduce:_
1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Choose big area (a bit less then 100 000 sq km)
3 Choose All Keywords, all Data Services
3 Try to Search Map until timeout error occurred

_Result:_
Timeout error message appeared.  Error message consider typo in word 'occurred'.
(refer to screenshot 739)

_Expected result:_
Error message: "An error occurred: timeout. Please limit search area or Keywords. Please contact Support if the problem persists."

**Comment by Stref** [comment]
![739](https://cloud.githubusercontent.com/assets/13001938/8308400/2c760972-19cd-11e5-86e3-091de2dca7a5.png)

**Comment by ghost** [comment]
BCC - 26-Jun-2016 - Recommend: Fix 

Fix applied to my local build...

**Comment by ghost** [comment]
Review Meeting Findings 01-Jul-2015

Proposed fix accepted as is...

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Issue fixed, warning message edited (see screenshot attached)
![150](https://cloud.githubusercontent.com/assets/13001938/9270175/35eee504-4278-11e5-8ff2-aa28e44d2208.png)

Closed
